name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      -completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ysfdocker1/first-image:latest

      - name: Delete old docker container
        run: sudo docker docker rm -f first-image-container || true

      - name: run Docker container
        run: sudo docker run -d -p 3000:3000 --name first-image-container ysfdocker1/first-image
